# -*- coding: utf-8 -*-
from . import re_property_amenity
from . import re_lease_service
from . import re_lease_plan
from . import re_lease_close_reason
from . import re_account_tax
from . import re_building
from . import re_property
from . import re_property_service
from . import re_lease_penalty_schedule
from . import re_penalty
from . import re_lease_saving_rule
from . import re_lease_tax_line
from . import re_lease_identity
from . import re_tenant_ref_log
from . import re_lease_log
from . import re_lease_line
from . import re_lease_template
from . import re_account_move
from . import res_partner
from . import re_lease
from . import re_lease_logic
from . import re_product
from . import re_dashboard
